### ISSUE TITLE
Adding README.md

### ISSUE THREAD

**Issue by zainabturkmen** [ShahirTurkmen/Web-site-Hero#1]
hey Shahir you have to add README.md file on your repo.
Thanks

Best Regards

**Comment by ShahirTurkmen** [comment]
hello

**Comment by ShahirTurkmen** [comment]
New branch
run below code in terminal
`git fetch origin
git checkout @main
`

**Comment by ShahirTurkmen** [comment]
![ddd](https://github.githubassets.com/assets/actions-secret-store-4121c7f05a49.svg)

**Comment by ShahirTurkmen** [comment]
> hey Shahir you have to add Read.md file on your repo. Thanks Best Regards

![added](https://github.githubassets.com/assets/actions-secret-store-4121c7f05a49.svg)
